import { Stack, type StackProps, Tags, Validations } from "aws-cdk-lib";
import { Construct } from "constructs";

import { createAuth } from "./auth.js";
import { createCompute } from "./compute.js";
import { createDataPlane } from "./data-plane.js";
import { createDeploymentIdentity } from "./deployment-identity.js";
import { createHttpApi } from "./http-api.js";
import { createNetwork } from "./network.js";
import { createObservability } from "./observability.js";
import { createReleaseParameters } from "./release-parameters.js";
import { createScaling } from "./scaling.js";

export class RecommendationSandboxStack extends Stack {
  public constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);
    if (this.region !== "ap-southeast-1") {
      throw new Error(`RecommendationSandboxStack requires ap-southeast-1, received ${this.region}`);
    }
    const githubRepository = this.node.tryGetContext("githubRepository") as string | undefined;
    if (githubRepository === undefined || !/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(githubRepository)) {
      throw new Error("CDK context githubRepository=owner/repository is required for scoped OIDC trust");
    }
    const release = createReleaseParameters(this);
    const network = createNetwork(this);
    const data = createDataPlane(this);
    const auth = createAuth(this);
    const compute = createCompute(this, network, data, release);
    createHttpApi(this, network, compute, auth);
    createScaling(this, compute, release);
    createObservability(this, compute, release);
    createDeploymentIdentity(this, release, githubRepository);

    const acknowledgements: ReadonlyArray<[string, string]> = [
      ["AwsSolutions-EC23", "The unresolved VPC CIDR is used only for DNS egress; no ingress is CIDR-open and no internet route exists."],
      ["AwsSolutions-S1", "The dedicated access-log sink is terminal and expires sandbox logs after 30 days; logging it recursively is impossible."],
      ["AwsSolutions-SMG4", "The generated non-customer runtime token rotates only through an immutable release deployment because no rotation Lambda is permitted in the no-NAT serving boundary."],
      ["AwsSolutions-COG1", "This user pool has no human/password users; only OAuth2 client_credentials is enabled."],
      ["AwsSolutions-COG2", "MFA does not apply to OAuth2 client_credentials machine identities."],
      ["AwsSolutions-COG8", "Plus-tier human sign-in threat protection does not apply to the synthetic M2M-only sandbox."],
      ["AwsSolutions-ECS2", "All direct environment values are non-secret immutable digests, resource names, localhost addresses, or bounded concurrency configuration; secret material uses ECS Secrets."],
      ["AwsSolutions-IAM5[Action::s3:GetObject*]", "CDK expands object-version reads; access remains resource-scoped to the evidence prefix."],
      ["AwsSolutions-IAM5[Action::s3:GetBucket*]", "CDK expands bucket metadata reads; access remains scoped to the evidence bucket."],
      ["AwsSolutions-IAM5[Action::s3:List*]", "Prefix-constrained evidence reconciliation requires the S3 list action family."],
      ["AwsSolutions-IAM5[Action::s3:DeleteObject*]", "The generated grant is defense-in-depth denied by the evidence bucket policy; application code cannot delete evidence."],
      ["AwsSolutions-IAM5[Action::s3:Abort*]", "Aborting incomplete multipart evidence uploads is required to avoid orphaned storage."],
      ["AwsSolutions-IAM5[Action::kms:ReEncrypt*]", "KMS grant action families are generated by CDK and remain scoped to the stack key."],
      ["AwsSolutions-IAM5[Action::kms:GenerateDataKey*]", "KMS grant action families are generated by CDK and remain scoped to the stack key."],
      ["AwsSolutions-IAM5[Resource::<EvidenceBucketFBA44255.Arn>/evidence/*]", "The wildcard is limited to object keys under the evidence prefix."],
      ["AwsSolutions-IAM5[Resource::*]", "X-Ray, CloudWatch PutMetricData, and ECR authorization-token APIs do not support resource-level permissions; action and namespace conditions bound them."],
    ];
    for (const [id, reason] of acknowledgements) {
      Validations.of(this).acknowledge({ id, reason });
    }

    Tags.of(this).add("Environment", "synthetic-sandbox");
    Tags.of(this).add("DataClass", "synthetic-only");
    Tags.of(this).add("ManagedBy", "CDK");
  }
}
