import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { LiveScenarioCase, TurnExpectation } from '../src/evaluation/liveQualityContracts.js';
import {
  renderFlutterGenUiScenarioDataFromPlan,
  type ScenarioCapturePlan,
} from '../src/genui/flutterScenarioData.js';
import {
  KFC_USE_CASE_DEFINITIONS,
  loadScenarioCorpus,
} from '../src/scenarios/scenarioScript.js';

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const conversationsRoot = join(repositoryRoot, 'ai-talent-tracks/fnb/conversations');
const docsPath = join(repositoryRoot, 'docs/testing-scenarios.md');
const capturePlanPath = join(repositoryRoot, 'services/kfc-agent-backend/fixtures/genui-scenario-capture-plan.json');
const flutterDataPath = join(
  repositoryRoot,
  'apps/kfc_live_monitor_flutter/integration_test/support/generated_genui_scenario_capture_data.dart',
);
const checkOnly = process.argv.includes('--check');
const scenarios = await loadScenarioCorpus(conversationsRoot);
const capturePlan = buildCapturePlan(scenarios);

const outputs = new Map<string, string>();
for (const scenario of scenarios) {
  outputs.set(
    join(conversationsRoot, scenario.fileName.replace(/\.json$/, '.md')),
    renderScenario(scenario),
  );
}
outputs.set(join(conversationsRoot, 'README.md'), renderIndex(scenarios));
outputs.set(docsPath, renderRunbook(scenarios));
outputs.set(capturePlanPath, `${JSON.stringify(capturePlan, null, 2)}\n`);
outputs.set(flutterDataPath, renderFlutterGenUiScenarioDataFromPlan(capturePlan, conversationsRoot));

const drift: string[] = [];
for (const [path, content] of outputs) {
  if (checkOnly) {
    const existing = await readFile(path, 'utf8').catch(() => '');
    if (existing !== content) drift.push(path);
  } else {
    await writeFile(path, content, 'utf8');
  }
}
if (drift.length > 0) {
  throw new Error(`Generated scenario docs are stale:\n${drift.join('\n')}`);
}

function renderScenario(scenario: LiveScenarioCase): string {
  const lines = [
    `# ${scenario.title}`,
    '',
    '> Generated from the adjacent JSON outcome contract. Do not edit this file directly.',
    '',
    `- ID: \`${scenario.id}\``,
    `- Channel: \`${scenario.channel}\``,
    `- Goal: ${scenario.goal}`,
    `- Final state: \`${scenario.finalState}\``,
    `- Setup: \`${JSON.stringify(scenario.setup)}\``,
    `- Use cases: ${scenario.useCases.map((id) => `\`${id}\``).join(', ')}`,
    '',
  ];
  for (const turn of scenario.turnExpectations) {
    lines.push(
      `## Customer turn ${turn.turnIndex}`,
      '',
      turn.input,
      '',
      `Use cases: ${turn.useCaseIds.map((id) => `\`${id}\``).join(', ')}`,
      '',
      ...renderOutcome(turn),
      '',
    );
  }
  return `${lines.join('\n').trim()}\n`;
}

function renderOutcome(turn: TurnExpectation): string[] {
  const { outcome } = turn;
  const lines = ['Observable outcome:'];
  const add = (label: string, values: readonly string[]) => {
    if (values.length > 0) lines.push(`- ${label}: ${values.map((value) => `\`${value}\``).join(', ')}`);
  };
  add('State must change', outcome.state.mustChange);
  add('State must not change', outcome.state.mustNotChange);
  add('Required effects', outcome.effects.required);
  add('Forbidden effects', outcome.effects.forbidden);
  add('Evidence', outcome.provenance.requiredEvidenceKinds);
  for (const fact of outcome.state.facts) {
    lines.push(
      `- Fact: \`${fact.source}.${fact.path}\` must \`${fact.operator}\`` +
      (fact.value === undefined ? '' : ` \`${JSON.stringify(fact.value)}\``),
    );
  }
  for (const collection of outcome.presentation.collections) {
    lines.push(
      `- Collection \`${collection.key}\`: scope \`${collection.scope}\`, minimum ${collection.minItems}, ` +
      `exact=${collection.exactVerifiedItems}, complete=${collection.requireComplete}` +
      (collection.maxItems !== undefined ? `, maximum ${collection.maxItems}` : '') +
      (collection.requiredCategories.length > 0
        ? `, required categories ${collection.requiredCategories.map((category) => `\`${category}\``).join(', ')}`
        : '') +
      (collection.requireCategoryTabs ? ', categorized tabs required' : '') +
      (collection.selectionLimit !== undefined ? `, selection limit ${collection.selectionLimit}` : ''),
    );
  }
  if (outcome.presentation.genUi.allowedWidgetKinds.length > 0) {
    lines.push(
      `- GenUI (${outcome.presentation.genUi.required ? 'required' : 'optional'}): one of ` +
      outcome.presentation.genUi.allowedWidgetKinds.map((kind) => `\`${kind}\``).join(', '),
    );
  }
  add('Required GenUI data paths', outcome.presentation.genUi.requiredDataPaths);
  add('Forbidden GenUI actions', outcome.presentation.genUi.forbiddenActions);
  if (outcome.provenance.requireOfficialSameReference) {
    lines.push('- Provenance: each governed evidence kind must use the same official reference as its claim');
  }
  lines.push(
    `- Persistence: transcript +${outcome.persistence.transcriptDelta}, ` +
    `contiguous events=${outcome.persistence.contiguousEvents}, ` +
    `checkpoint=${outcome.persistence.checkpointRequired}`,
  );
  lines.push(`- Turn latency ceiling: ${outcome.latency.maxTurnMs}ms`);
  return lines;
}

function renderIndex(scenarios: LiveScenarioCase[]): string {
  const turnCount = scenarios.reduce((total, scenario) => total + scenario.turnExpectations.length, 0);
  return [
    '# KFC outcome scenario corpus',
    '',
    '> Generated from `*.json`. JSON is the only authored scenario and outcome source.',
    '',
    `The corpus contains ${scenarios.length} scenarios and ${turnCount} customer turns. ` +
    `Text and GenUI modes produce ${turnCount * 2} dataset examples.`,
    '',
    '## Authoritative use-case taxonomy',
    '',
    '| UC | Observable intent |',
    '|---|---|',
    ...KFC_USE_CASE_DEFINITIONS.map(({ id, name }) => `| ${id} | ${name} |`),
    '',
    '## Scenarios',
    '',
    ...scenarios.map((scenario) =>
      `- [${scenario.title}](./${scenario.fileName.replace(/\.json$/, '.md')}) — ` +
      `${scenario.turnExpectations.length} customer turns`),
    '',
  ].join('\n');
}

function renderRunbook(scenarios: LiveScenarioCase[]): string {
  return [
    '# KFC scenario qualification',
    '',
    '> Generated index and count contract. Scenario inputs and outcomes live only in ' +
    '`ai-talent-tracks/fnb/conversations/*.json`.',
    '',
    '## Canonical math',
    '',
    '- 9 scenarios',
    '- 48 customer turns',
    '- 96 Text/GenUI dataset examples',
    '- 3 unchanged repetitions',
    '- 54 scenario-mode runs per provider',
    '- 288 turn-mode evaluations per provider',
    '',
    'The evaluator compares observable state, effects, exact verified facts and collections, ' +
    'provenance, receipts, persistence, latency, Text/GenUI fact parity, and cross-provider ' +
    'structured-fact parity. It does not grade ' +
    'planner routes, tool order, provider wording, or fixed customer-language phrases.',
    '',
    '## Offline checks',
    '',
    '```bash',
    'cd services/kfc-agent-backend',
    'npx tsx scripts/generate-scenario-docs.ts --check',
    'npx vitest run test/scenarios/scenario-script.test.ts test/scenarios/scenario-coverage-ledger.test.ts test/evaluation/live-quality-dataset.test.ts test/evaluation/live-quality-runner.test.ts',
    '```',
    '',
    'The paid live matrix remains blocked until the provider-neutral single-agent adapter is integrated. ' +
    'Do not synchronize the v2 LangSmith dataset before the reviewed corpus digest and runtime adapter are accepted.',
    '',
    '## Scenarios',
    '',
    ...scenarios.map((scenario) =>
      `- [${scenario.title}](../ai-talent-tracks/fnb/conversations/${scenario.fileName.replace(/\.json$/, '.md')})`),
    '',
  ].join('\n');
}

function buildCapturePlan(scenarios: LiveScenarioCase[]): ScenarioCapturePlan {
  return {
    version: 4,
    description:
      'Generated GenUI render plan for all canonical outcome scenarios. JSON outcome contracts are authoritative.',
    scenarios: scenarios.map((scenario) => {
      const expectedWidgetsByUserTurn: Record<string, string> = {};
      const acceptableWidgetsByUserTurn: Record<string, string[]> = {};
      const requiredWidgetKinds = new Set<string>();
      for (const turn of scenario.turnExpectations) {
        const genUi = turn.outcome.presentation.genUi;
        if (!genUi.required) {
          if (genUi.allowedWidgetKinds.length > 0) {
            acceptableWidgetsByUserTurn[String(turn.turnIndex)] = [
              'chatTranscript',
              ...genUi.allowedWidgetKinds,
            ];
          }
          continue;
        }
        const [primary, ...alternatives] = genUi.allowedWidgetKinds;
        if (!primary) {
          throw new Error(`${scenario.fileName}#${turn.turnIndex} requires GenUI without an allowed widget`);
        }
        expectedWidgetsByUserTurn[String(turn.turnIndex)] = primary;
        if (alternatives.length > 0) {
          acceptableWidgetsByUserTurn[String(turn.turnIndex)] = [...genUi.allowedWidgetKinds];
        } else {
          requiredWidgetKinds.add(primary);
        }
      }
      return {
        fileName: scenario.fileName,
        requiredWidgetKinds: [...requiredWidgetKinds],
        expectedWidgetsByUserTurn,
        ...(Object.keys(acceptableWidgetsByUserTurn).length > 0
          ? { acceptableWidgetsByUserTurn }
          : {}),
      };
    }),
  };
}
