import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

interface ScenarioCapturePlan {
  scenarios: Array<{ fileName: string }>;
}

interface ScenarioScript {
  id: string;
  turns: Array<{
    index: number;
    speaker: 'User' | 'Bot';
    text: string;
    useCases?: string[] | undefined;
  }>;
}

export function syncFlutterGenUiScenarioData(
  capturePlanPath: string,
  scenariosRoot: string,
  outputPath: string,
): void {
  const capturePlan = readJson<ScenarioCapturePlan>(capturePlanPath);
  const scenarioEntries = capturePlan.scenarios.map(({ fileName }) => {
    const script = readJson<ScenarioScript>(resolve(scenariosRoot, fileName));
    const userScript = {
      id: script.id,
      turns: script.turns.filter((turn) => turn.speaker === 'User'),
    };
    return `  ${JSON.stringify(fileName)}: ${dartRawJson(userScript)},`;
  });

  const output = [
    '// Generated test data for backend-backed customer-chat GenUI integration tests.',
    '// Source: backend GenUI scenario capture plan.',
    '// Source: ai-talent-tracks/fnb/conversations/*.json user turns only.',
    '// Regenerated by the live GenUI integration proof runner. Do not edit manually.',
    '',
    `const genUiScenarioCapturePlanJson = ${dartRawJson(capturePlan)};`,
    '',
    'const genUiScenarioJsonByFileName = <String, String>{',
    ...scenarioEntries,
    '};',
    '',
  ].join('\n');

  writeFileSync(outputPath, output);
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, 'utf8')) as T;
}

function dartRawJson(value: unknown): string {
  const json = JSON.stringify(value, null, 2);
  if (json.includes("'''")) {
    throw new Error('Scenario data cannot contain a triple single quote in a Dart raw string.');
  }
  return `r'''${json}'''`;
}
